#!/usr/bin/env bash
# This script shows information about subdomains.

function domain_information {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi
    
    for sub in "$(subdomains[@])"; do
        record_type=$(dig "$sub. $domain" | awk '/ANSWER SECTION:/ {getline; print $4}')
        destination=$(dig "$sub. $domain" | awk '/ANSWER SECTION:/ {getline; print $5}')
        echo "The subdomain $sub is a $record and points to $destination"
    done

}

domain_information "$1" "$2"
