#!/usr/bin/env bash
# This script shows information about subdomains.

my_domain_information() {
    local domain="$1"
    local subdomain="$2"
    local line
    line=$(dig "$subdomain"."$domain" | awk '/ANSWER SECTION:/ {getline; print; getline; print}')
    echo "$subdomain $line" | awk '{printf "The subdomain %s is a %s record and points to %s\n", $1, $2, $3}'
}

if [ "$#" -eq 1 ]; then
    my_domain_information "$1" "www"
    my_domain_information "$1" "lb-01"
    my_domain_information "$1" "web-01"
    my_domain_information "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    my_domain_information "$1" "$2"
fi