#!/usr/bin/env bash
# A script that installs nginx server on an ubuntu linux distro.

sudo apt-get update -y

sudo apt-get install nginx -y

sudo service nginx restart

sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.html /var/www/html/index.html.bckp

echo -e "Hello World!" | dd status=none of=/var/www/html/index.html

sudo service nginx restart
