#!/usr/bin/env bash

sudo apt update -y

sudo apt install -y nginx

sudo sed -i 's/\blisten 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

sudo nginx -s reload

echo 'Hello World!' > /var/www/html/index.html
