#!/usr/bin/env bash
# A bash script that enables '/redirect_me' to redirect to another page.

sudo apt-get update -y

sudo apt-get install nginx -y

sudo service nginx start

sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.html /var/www/html/index.html.bckp

echo -e "Hello World!" > /var/www/html/index.html

sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
