#!/usr/bin/env bash
# Customizing a 404-error_page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

my_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/FelixKorirr permanent;"
sudo sed -i "s/server_name _;/$my_string/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
my_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$my_string/" /etc/nginx/sites-enabled/default

sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart
