#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get -y update
apt-get -y install haproxy

echo '
frontend devkorir.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 323183-web-01 100.25.102.196
        server 323183-web-02 52.86.109.248
' >> /etc/haproxy/haproxy.cfg

service haproxy restart
