#!/usr/bin/env bash
# configure a Haproxy on a load balancer

# Install haproxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure haproxy config file
server_config=\
"
frontend devkorir.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 323183-web-01 100.25.102.196
        server 323183-web-02 52.86.109.248
" 
echo "$server_config" >> /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the haproxy config file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart haproxy service
sudo service haproxy restart
