#!/usr/bin/env bash

#Generate the current date
current_date = (date + "%d-%m-%Y")

#create mysqldump of all my databases 
sudo mysqldump -u root -p --all-databases > backup.sql

#Compress the mysqldump file
tar -czvf $current_date.tar.gz  backup.sql
