#!/usr/bin/env bash
#This script displays the time for 12hrs & 59 minutes
Hours=0
while [ $Hours -lt 12 ]
do
    echo Hour: $Hours
    Minutes=1
        while [ $Minutes -le 59 ]
        do
            echo $Minutes
            ((Minutes++))
        done
    ((Hours++))
done
